### ISSUE TITLE
Apache config gets corrupted from time to time

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/utcapiproxy#6]
Modify the laravel_project.conf contents so that they look like this maybe?

NameVirtualHost *:8080
Listen 8080

<VirtualHost *:8080>
    ServerAdmin admin@example.com
    ServerName laravel.dev
    ServerAlias www.laravel.dev
    DocumentRoot /home/user/projects/laravel_project/public
    
    <Directory /home/user/projects/laravel_project/public/>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
            Require all granted
    </Directory>
    
    LogLevel debug
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

https://phpraxis.wordpress.com/2016/08/02/steps-for-configuring-laravel-on-apache-http-server/

https://github.com/UTCWeb/utcapiproxy/blob/develop/public/.htaccess

**Comment by UTCGilligan** [comment]
I think this was probably due to the automated server config cron that copies config periodically from 11 to 12. This has been disabled so it can be run manually whenever server config needs to be copied from 11 to 12.
